CREATE TABLE IF NOT EXISTS crisis_centers
(
    id          INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT,
    description TEXT,
    phones      TEXT,
    email       TEXT,
    address     TEXT,
    photo       TEXT,
    locale      TEXT
);