CREATE TABLE IF NOT EXISTS persons
(
    id              INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      TEXT,
    last_name       TEXT,
    position        TEXT,
    photo           TEXT,
    company_info_id NUMERIC
);