CREATE TABLE IF NOT EXISTS funds
(
    id          INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT,
    description TEXT,
    phones      TEXT,
    email       TEXT,
    address     TEXT,
    site        TEXT,
    photo       TEXT,
    locale      TEXT
);